/* Project settings */
var hmAnimate = true;
var hmPopupSticky = true;
var hmImageLightbox = true;
var hmVideoLightbox = true;
var hmLightboxConstrained = true;
var hmForceRedirect = false;
var hmTocSingleClick = true;
var autocollapse = false;
var gaaccount = "UA-6580392-2";
var initialtocstate = "collapsed";
